version: "2"
services:
  redis:
    image: "redis:alpine"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./.env
    environment:
      - NODE_ENV=production
      - PORT=3000
      - REDIS_URL=redis://redis:6379
      - CALLBACK_URL=http://localhost:3000/auth
    ports:
      - "3000:3000"
    restart: always
    container_name: prep-manager
    depends_on:
      - redis
